name: vis-tutorial
channels:
    - conda-forge
    - defaults
dependencies:
    - basemap=1.1.0
    - basemap-data-hires=1.1.0
    - bokeh=0.12.9
    - cartopy=0.15.1
    - holoviews=1.8.4
    - matplotlib=2.1.0
    - notebook=5.1.0
    - numpy=1.13.1
    - pandas=0.20.3
    - plotly=2.0.15
    - python=3.6
    - scipy=0.19.1
    - seaborn=0.8.1
    - statsmodels=0.8.0
    - xarray=0.9.6
    - pip:
        - cufflinks==0.12.0
